font_size 16
term xterm-kitty
include tokyo-night.conf

# Fira code
font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
disable_ligatures always

# Window
remember_window_size yes

# Hide mouse when typing
mouse_hide_wait -1
